# Generated by Django 4.2.9 on 2025-02-15 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'student'), ('2', 'teacher')], default='1', max_length=20)),
                ('image', models.FileField(blank=True, upload_to='images')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('duration', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(null=True, upload_to='')),
                ('date_material', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('talkto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_talkto', to='elearningapp.appuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user', to='elearningapp.appuser')),
            ],
        ),
    ]
