# Generated by Django 4.2.9 on 2025-02-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0002_alter_appuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material',
            field=models.FileField(upload_to='material_course'),
        ),
    ]
